console.log("d");
document.getElementById("1").onclick=function(){
    document.getElementById("input").value+=1;
}
document.getElementById("2").onclick=function(){
    document.getElementById("input").value+=2;
}
document.getElementById("3").onclick=function(){
    document.getElementById("input").value+=3;
}
document.getElementById("4").onclick=function(){
    document.getElementById("input").value+=4;
}
document.getElementById("5").onclick=function(){
    document.getElementById("input").value+=5;
}
document.getElementById("6").onclick=function(){
    document.getElementById("input").value+=6;
}
document.getElementById("7").onclick=function(){
    document.getElementById("input").value+=7;
}
document.getElementById("0").onclick=function(){
    document.getElementById("input").value+=0;
}
document.getElementById("8").onclick=function(){
    document.getElementById("input").value+=8;
}
document.getElementById("9").onclick=function(){
    document.getElementById("input").value+=9;
}
document.getElementById("+").onclick=function(){
    document.getElementById("input").value+="+";
}
document.getElementById("-").onclick=function(){
    document.getElementById("input").value+="-";
}
document.getElementById("*").onclick=function(){
    document.getElementById("input").value+="*";
}
document.getElementById("/").onclick=function(){
    document.getElementById("input").value+="/";
}
document.getElementById(".").onclick=function(){
    document.getElementById("input").value+=".";
}
document.getElementById("AC").onclick=function(){
    document.getElementById("input").value="";
}
